name: zappis
description: Zappis - EV Charging App for Ethiopia

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.2.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  provider: ^6.1.1
  flutter_map: ^6.1.0
  flutter_map_cache: ^1.3.0
  latlong2: ^0.9.0
  intl: ^0.19.0
  qr_flutter: ^4.1.0
  url_launcher: ^6.2.2
  google_fonts: ^6.1.0
  shared_preferences: ^2.2.2
  geolocator: ^10.1.0
  flutter_cache_manager: ^3.3.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1

flutter:
  uses-material-design: true
  
  assets:
    - assets/images/
  
  fonts:
    - family: Magnetico
      fonts:
        - asset: assets/fonts/Magnetico-Regular.ttf
    - family: Urbanist
      fonts:
        - asset: assets/fonts/Urbanist-Regular.ttf
        - asset: assets/fonts/Urbanist-Medium.ttf
          weight: 500
        - asset: assets/fonts/Urbanist-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Urbanist-Bold.ttf
          weight: 700
